version: "3"
services:
  app:
    container_name: go-blog-api_app
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - go-blog-postgres
    networks:
      - go-blog-network

  go-blog-postgres:
    image: postgres:latest
    container_name: go-blog-api_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - go-blog-network

volumes:
  api:
  database_postgres:


networks:
  go-blog-network:
    driver: bridge