version: "3"
services:
  app:
    container_name: go-api-setup
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - api:/usr/src/app/

volumes:
  api:
  database_mysql:
